# Generated by Django 5.2.8 on 2025-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.FloatField(default=0),
        ),
    ]
